# Generated by Django 5.2.5 on 2025-08-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='upadet_at',
            new_name='updated_at',
        ),
    ]
